### ISSUE TITLE
Typescript error: .openDrawer() does not exist on type 'NavigationProp'

### ISSUE THREAD

**Issue by batjko** [markscodingspot/ui-kitten-nav#1]
Hi,

I am using Typescript in my project (react-navigation comes with types out of the box), but otherwise followed your instructions to the letter.

It all works fine in the emulator, too. :partying_face: 
But it's worth noting that there seems to be a missing prop for the `useNavigation` hook.
It's not an issue with your code, just with react-navigation, it seems, which people using Typescript will notice when following your video, so i thought I register it here for others to find.

![image](https://user-images.githubusercontent.com/7287076/130701595-f3d37a89-7bd7-4db4-9838-4c8097401d07.png)

These are the props the `navigation` comes with:

![image](https://user-images.githubusercontent.com/7287076/130701646-753b03fd-7bd6-4404-8a9b-60671b67c704.png)

For reference, there is a related issue on the react-native repo: https://github.com/react-navigation/hooks/issues/42

**Comment by batjko** [comment]
I just found that this comment has the right solution: https://github.com/react-navigation/react-navigation/issues/6592#issuecomment-581399018

Apparently, the `openDrawer()` method now exists on the `@react-navigation/native` package, and needs to be dispatched by the `navigation` hook.

So this works:

![image](https://user-images.githubusercontent.com/7287076/130702479-2d2c8f1d-8876-44c2-9d2c-f4063ec5f2cd.png)

**Comment by ghost** [comment]
Thank you @batjko

**Comment by parmarravi** [comment]
Close drawer do not work with this method
